@startuml
!include IComponent.puml

class ComponentRegistry
{
	#Components Dictionary<string, PackedScene>
	+RegisterComponent(PackedScene componentScene)
	+RegisterComponentsAtPath(string path, bool searchInSubdirectories)
	+Node InstanceComponent(string componentName)
}

@enduml